### ISSUE TITLE
Inconsistencies

### ISSUE THREAD

**Issue by RiderExMachina** [dasgeekchannel/AutoInstallBashScripts#9]
There are a few inconsistencies in this script: 

1. Both `apt` and `apt-get` are used
2. Despite needing to run the script with escalated privileges `sudo` is ran for many packages 
3. All SNAP programs install `snapd` before installing the snap package, despite `snapd` being its own install near the top of the script.

Here is what I advise:

1. Standardize on `apt` or `apt-get`
2. Either remove the need for escalated privileges at the start of the script or remove the odd `sudo` commands
3. Make the SNAP packages rely on having the script's `snapd` installed (if possible).

**Comment by dasgeekchannel** [comment]
I leave installing snapd in there due to people trying to install snaps and getting errors. So if you pick a snap it automatically tries to install snapd. There probably is a better way for it to check and perhaps ask. I will investigate. Sudo being in there is just bad habit. Will clean up the code with next release.

**Comment by RiderExMachina** [comment]
Here's what I would recommend:

```
if ! [[ -e /usr/lib/snapd ]] ; then
do
    apt install snapd
done

snap install [program]
```
